### ISSUE TITLE
XML Schema 1.1 ?

### ISSUE THREAD

**Issue by c-alpha** [eyedouble/erlxml#1]
You state that "validation is done by `xmerl_xsd` module". So I guess that means XML Schema 1.1 is not supported?

**Comment by ivanwel** [comment]
Hi, Have look at the xmerl_xsd docs, for compatability if this supports it erlxml will be able to work with it.On 30 Jul 2021 6:03 pm, Alexander Adolf ***@***.***> wrote:
You state that "validation is done by xmerl_xsd module". So I guess that means XML Schema 1.1 is not supported?

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
On 30 Jul 2021 6:03 pm, Alexander Adolf ***@***.***> wrote:
You state that "validation is done by xmerl_xsd module". So I guess that means XML Schema 1.1 is not supported?

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
On 30 Jul 2021 6:03 pm, Alexander Adolf ***@***.***> wrote:
You state that "validation is done by xmerl_xsd module". So I guess that means XML Schema 1.1 is not supported?

**Comment by c-alpha** [comment]
> Hi, Have look at the xmerl_xsd docs, for compatability if this supports it erlxml will be able to work with it.

http://erlang.org/doc/man/xmerl_xsd.html says:
```
Interface module for XML Schema validation. It handles the W3.org
specifications of XML Schema second edition 28 october 2004.
```

That clearly means "W3C XML Schema 1.0 only". If it had supported 1.1, it would have needed to refer to the 5 April 2012 revision of the W3C TR; but then, it doesn't.

In practice, this probably means: "if you're looking at some heavy XML lifting, you're on the way to Java."
